### ISSUE TITLE
Can I speak or email with a developer?

### ISSUE THREAD

**Issue by HeatonJL** [prabhuramachandran/vixen#26]
I have questions about the capabilities of the application.  I have lots of scientists around the state of California, that are using camera traps in their research, and I need something to aid in the organization of all the photos.

**Comment by prabhuramachandran** [comment]
There is a mailing list for this project here: https://groups.google.com/forum/#!forum/vixen
Our personal email addresses are also available from either our github profile (https://github.com/prabhuramachandran/) or our paper.  In general we would prefer emails to the mailing list as other users could potentially answer questions.  I am closing this since it is not really an issue.

**Comment by HeatonJL** [comment]
I tried to go to the Google group yesterday, and I received an error message saying that either the group didn’t exist, or I didn’t have permission to open it.

**Comment by kadambarid** [comment]
You need to be a member of the group to post, IIRC - https://groups.google.com/forum/#!forum/vixen

If you're having any difficulty signing up, feel free to contact Prabhu (prabhu<at>aero<dot>iitb<dot>ac<dot>in) or me (kadambari<dot>devarajan<at>gmail<dot>com). Like Prabhu said, we'd appreciate it if you tried posting on the group first though.

**Comment by HeatonJL** [comment]
I can’t get to the group itself.  If I click the link you provide, I get an error saying:

“This group either doesn’t exist, or you don’t have permission to access it.  If you’re sure this group exists, contact the Owner of the group and ask them to give you access”

I have what I hope is a fairly simple question:

Can your product scale to meet the needs of scientists spread out over the entirety of the state of California?  Can your product be setup in a centralized manner, so that all of these scientists can access a central point, to share camera trap photos and data?

**Comment by kadambarid** [comment]
I'm afraid ViXeN doesn't quite support collaboratively working on the same project. There are mechanisms to work around this but it still will not be possible to have a central database that can be edited in real time by multiple people simultaneously (if I understood your question correctly).

**Comment by HeatonJL** [comment]
That’s what I was afraid of, thank you for your response.
