### ISSUE TITLE
Program fails to initialize - syntax error in 3.7

### ISSUE THREAD

**Issue by deniederhut** [prabhuramachandran/vixen#27]
**Describe the bug**
Program fails with syntax error in python >= 3.7. Depending on your philosophical perspective, this is either a bug about using a keyword as a name or a bug about allowing installs for unsupported python versions.

**Software Version**
ViXeN version: 1.0rc3.dev0, from master, via pip

**To Reproduce**
Run vixen console entry point

**Expected behavior**
Program executes

**Log file**

Relevant logs

```
INFO|2019-07-18 21:59:05,564|vixen.cli|**** Starting ViXeN ****
INFO|2019-07-18 21:59:05,564|vixen.cli|Project root: /Users/dillon/.vixen
INFO|2019-07-18 21:59:05,564|vixen.cli|ViXeN version: 1.0rc3.dev0
INFO|2019-07-18 21:59:05,564|vixen.cli|Runing from /Users/dillon/githubpackages/vixen/vixen
INFO|2019-07-18 21:59:05,564|vixen.cli|uname_result(system='Darwin', node='Majora.local', release='17.7.0', version='Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64', machine='x86_64', processor='i386')
INFO|2019-07-18 21:59:05,565|vixen.cli|vixen called as: ['/Users/dillon/anaconda/envs/vixen-test/bin/vixen']
INFO|2019-07-18 21:59:05,565|vixen.cli|Parsed command line args: Namespace(console=False, dev=False, port=None, version=False)
ERROR|2019-07-18 21:59:05,567|vixen.cli|Uncaught exception
Traceback (most recent call last):
  File "/Users/dillon/anaconda/envs/vixen-test/bin/vixen", line 11, in <module>
    load_entry_point('vixen', 'console_scripts', 'vixen')()
  File "/Users/dillon/githubpackages/vixen/vixen/cli.py", line 95, in main
    view(dev=opts.dev, port=opts.port)
  File "/Users/dillon/githubpackages/vixen/vixen/cli.py", line 63, in view
    from vixen.vixen_ui import main
  File "/Users/dillon/githubpackages/vixen/vixen/vixen_ui.py", line 51
    async = False
          ^
SyntaxError: invalid syntax
```

**Additional context**
You may wish to consider specifying a `python_requires` in your setup.py.

xref https://github.com/openjournals/joss-reviews/issues/1501

**Comment by prabhuramachandran** [comment]
This is an issue with the jigna package and I will need to update that and push a new release of it.  The problem was with the newly introduced async keyword which has broken the package.  It should be fixed.  I am slow to do this.

**Comment by deniederhut** [comment]
Hey Prabhu! Just wanted to check in to ask how things were going.

**Comment by prabhuramachandran** [comment]
I had started some work last week but I had to travel to the UK for a workshop and then fell very sick on the way back.  I have recovered but my semester just started, so I will be able to get to the issues by the coming weekend.  In the meanwhile it may be best to use the binaries to test the software perhaps?

**Comment by prabhuramachandran** [comment]
I just pushed a simple temporary fix for this until I get time to fix jigna.
