### ISSUE TITLE
Paper: link to the documentation

### ISSUE THREAD

**Issue by deniederhut** [prabhuramachandran/vixen#28]
In both the readme and the paper submitted to JOSS, the documents are linked via the display name `https://vixen.rtfd.io`. This is a fun little inside joke, but the `f` stands for a word which is not generally considered professional. I might suggest using the equivalent `vixen.readthedocs.io` instead.

xref https://github.com/openjournals/joss-reviews/issues/1501

**Comment by prabhuramachandran** [comment]
Thanks.  I always thought the 'f' stood for fine.  ;-) I think it is unfortunate that in general offensive language is assumed when a nicer word is possible.  Having said that I will change the link to the longer version in the interest of not causing offense.  Will update the ticket when this is done.
